"""
FTG Canonical Metrics Package
=============================

This package contains the SINGLE SOURCE OF TRUTH for all
derived financial metrics used by dashboards, APIs, and NLQ.

All metrics are computed strictly from versioned JSON outputs
generated by the GitHub ETL pipeline.

No database access is permitted in this package.
"""

